static void Cpu_LoadW_Reg(Byte dst, Byte src)
{
  
}

static void Cpu_LoadB_Reg(Byte dst, Byte src)
{
}

static void Cpu_LoadW_Imm(Byte dst, Word reg)
{
}

static void Cpu_LoadB_Imm(Byte dst, Word reg)
{
}

static void Cpu_StoreW_Reg(Byte dst, Byte src)
{
}

static void Cpu_StoreB_Reg(Byte dst, Byte src)
{
}

static void Cpu_StoreW_Imm(Word dst, Byte src)
{
}

static void Cpu_StoreB_Imm(Word dst, Byte src)
{
}
