static void Cpu_AndW_Reg(Byte dst, Byte src)
{
}

static void Cpu_AndB_Reg(Byte dst, Byte src)
{
}

static void Cpu_AndW_Imm(Byte dst, Word src)
{
}

static void Cpu_AndB_Imm(Byte dst, Word src)
{
}




static void Cpu_OrW_Reg(Byte dst, Byte src)
{
}

static void Cpu_OrB_Reg(Byte dst, Byte src)
{
}

static void Cpu_OrW_Imm(Byte dst, Word src)
{
}

static void Cpu_OrB_Imm(Byte dst, Word src)
{
}


static void Cpu_XorW_Reg(Byte dst, Byte src)
{
}

static void Cpu_XorB_Reg(Byte dst, Byte src)
{
}

static void Cpu_XorW_Imm(Byte dst, Word src)
{
}

static void Cpu_XorB_Imm(Byte dst, Word src)
{
}


static void Cpu_NotW_Reg(Byte dst)
{
}

static void Cpu_NotB_Reg(Byte dst)
{
}




static void Cpu_ShiftLeftW_Reg(Byte dst, Byte src)
{
}

static void Cpu_ShiftLeftB_Reg(Byte dst, Byte src)
{
}




static void Cpu_ShiftRightW_Reg(Byte dst, Byte src)
{
}

static void Cpu_ShiftRightB_Reg(Byte dst, Byte src)
{
}




static void Cpu_RollLeftW_Reg(Byte dst, Byte src)
{
}

static void Cpu_RollLeftB_Reg(Byte dst, Byte src)
{
}




static void Cpu_RollRightW_Reg(Byte dst, Byte src)
{
}

static void Cpu_RollRightB_Reg(Byte dst, Byte src)
{
}

