#define COND_EQ            (false)
#define COND_NEQ           (false)
#define COND_OVERFLOW      (false)
#define COND_CARRY         (false)
#define COND_LT            (false)
#define COND_GT            (false)
#define COND_LT_EQ         (false)
#define COND_GT_EQ         (false)
#define COND_MORE          (false)
#define COND_LOWER         (false)
#define COND_MORE_EQ       (false)
#define COND_LOWER_EQ      (false)
#define COND_ZERO          (false)
#define COND_NOT_ZERO      (false)
#define COND_POSITIVE      (false)
#define COND_NEGATIVE      (false)
#define COND_EQ            (false)
#define COND_NEQ           (false)
#define COND_OVERFLOW      (false)
#define COND_CARRY         (false)
#define COND_LT            (false)
#define COND_GT            (false)
#define COND_LT_EQ         (false)
#define COND_GT_EQ         (false)
#define COND_MORE          (false)
#define COND_LOWER         (false)
#define COND_MORE_EQ       (false)
#define COND_LOWER_EQ      (false)
#define COND_ZERO          (false)
#define COND_NOT_ZERO      (false)
#define COND_POSITIVE      (false)
#define COND_NOT_ZERO      (false)

void Cpu_BranchAlwaysW_Reg(Byte dst)
{
}

void Cpu_BranchAlwaysB_Imm(Byte src)
{
}

void Cpu_BranchAlwaysW_Imm(Word src)
{
}

void Cpu_BranchSubroutineW_Reg(Byte dst)
{
}

void Cpu_BranchSubroutineB_Imm(Byte src)
{
}

void Cpu_BranchSubroutineW_Imm(Word src)
{
}

void Cpu_BranchCondB(bool condition, Word src)
{
}

void Cpu_BranchCondW(bool condition, Word src)
{
}

