static void Cpu_AddW_Reg(Byte dst, Byte src)
{
}

static void Cpu_AddB_Reg(Byte dst, Byte src)
{
}

static void Cpu_AddW_Imm(Byte dst, Word src)
{
}

static void Cpu_AddB_Imm(Byte dst, Word src)
{
}





static void Cpu_SubW_Reg(Byte dst, Byte src)
{
}

static void Cpu_SubB_Reg(Byte dst, Byte src)
{
}

static void Cpu_SubW_Imm(Byte dst, Word src)
{
}

static void Cpu_SubB_Imm(Byte dst, Word src)
{
}







static void Cpu_AddCarryW_Reg(Byte dst, Byte src)
{
}

static void Cpu_AddCarryB_Reg(Byte dst, Byte src)
{
}

static void Cpu_AddCarryW_Imm(Byte dst, Word src)
{
}

static void Cpu_AddCarryB_Imm(Byte dst, Word src)
{
}




static void Cpu_SubCarryW_Reg(Byte dst, Byte src)
{
}

static void Cpu_SubCarryB_Reg(Byte dst, Byte src)
{
}

static void Cpu_SubCarryW_Imm(Byte dst, Word src)
{
}

static void Cpu_SubCarryB_Imm(Byte dst, Word src)
{
}





static void Cpu_AddQuickW_Imm(Byte dst, Byte src)
{
}

static void Cpu_AddQuickB_Imm(Byte dst, Byte src)
{
}






static void Cpu_SubQuickW_Imm(Byte dst, Byte src)
{
}

static void Cpu_SubQuickB_Imm(Byte dst, Byte src)
{
}






static void Cpu_IncW_Imm(Byte dst)
{
}


static void Cpu_IncB_Imm(Byte dst)
{
}




static void Cpu_DecW_Imm(Byte dst)
{
}


static void Cpu_DecB_Imm(Byte dst)
{
}






static void Cpu_MulW_Reg(Byte dst, Byte src)
{
}

static void Cpu_MulB_Reg(Byte dst, Byte src)
{
}

static void Cpu_MulW_Imm(Byte dst, Word src)
{
}

static void Cpu_MulB_Imm(Byte dst, Word src)
{
}





static void Cpu_DivW_Reg(Byte dst, Byte src)
{
}

static void Cpu_DivB_Reg(Byte dst, Byte src)
{
}

static void Cpu_DivW_Imm(Byte dst, Word src)
{
}

static void Cpu_DivB_Imm(Byte dst, Word src)
{
}




static void Cpu_ModW_Reg(Byte dst, Byte src)
{
}

static void Cpu_ModB_Reg(Byte dst, Byte src)
{
}

static void Cpu_ModW_Imm(Byte dst, Word src)
{
}

static void Cpu_ModB_Imm(Byte dst, Word src)
{
}




static void Cpu_NegW_Reg(Byte dst)
{
}

static void Cpu_NegB_Reg(Byte dst)
{
}
