// Automatically generated file
namespace DX8 { class Api { 
  public const int A = 0;
  public const int X = 1;
  public const int Y = 2;
  public const int Z = 3;
  public const int W = 4;
  public const int Pc = 5;
  public const int Flags = 6;
  public const int Stack = 7;
  public const int LastOpcode = 8;
  public const int LastOperand = 9;
  public const int CrtDirty = 10;
  public const int GpuTimer = 11;
  public const int ChipAddr = 12;
  public const int ProgramAddr = 13;
  public const int SharedAddr = 14;
  public const int CpuHalt = 15;
  public const int Rom = 100;
  public const int ChipRam = 101;
  public const int SharedRam = 102;
  public const int FloppyDisk = 103;
  public const int GpuCrt = 104;
  public const int SfxBuffer = 105;
  public const int HardReset = 201;
  public const int SoftReset = 202;
  public const int CycleFn = 203;
  public const int InsertDisk = 204;
  public const int RemoveDisk = 205;
}}
