
#define DX8_GFX_RESOLUTION              (512)
#define DX8_GFX_SCANLINES               (312)
#define DX8_GFX_WIDTH                   (320)
#define DX8_GFX_HEIGHT                  (256)
#define DX8_GFX_BYTES_PER_PIXEL         (3)
#define DX8_GFX_PIXELS_PER_GFX_CYCLE    (8)
#define DX8_GFX_BUFFER_SIZE             (DX8_GFX_WIDTH * DX8_GFX_HEIGHT * DX8_GFX_BYTES_PER_PIXEL)
#define DX8_GFX_CYCLES_PER_SCANLINE     (DX8_GFX_RESOLUTION / DX8_GFX_PIXELS_PER_GFX_CYCLE)
#define DX8_GFX_CYCLES_PER_FRAME        (DX8_GFX_SCANLINES * DX8_GFX_CYCLES_PER_SCANLINE)
#define DX8_GFX_HBLANK_PX               (DX8_GFX_RESOLUTION - DX8_GFX_WIDTH)
#define DX8_GFX_HBLANK_LEFT_PX          (DX8_GFX_HBLANK_PX / 2)
#define DX8_GFX_HBLANK_RIGHT_PX         (DX8_GFX_HBLANK_PX / 2)
#define DX8_GFX_HBLANK_LEFT             (DX8_GFX_HBLANK_LEFT_PX / 8)
#define DX8_GFX_HBLANK_RIGHT            (DX8_GFX_HBLANK_RIGHT_PX / 8)
#define DX8_GFX_HBLANK_START            ((DX8_GFX_HBLANK_LEFT_PX + DX8_GFX_WIDTH) / DX8_GFX_PIXELS_PER_GFX_CYCLE)
#define DX8_GFX_HBLANK_CYCLES           (DX8_GFX_HBLANK_PX / DX8_GFX_PIXELS_PER_GFX_CYCLE)
#define DX8_GFX_VBLANK_SCANLINES        (DX8_GFX_SCANLINES - DX8_GFX_HEIGHT)
#define DX8_GFX_VBLANK_TOP_SCANLINES    (DX8_GFX_VBLANK_SCANLINES / 2)
#define DX8_GFX_VBLANK_BOTTOM_SCANLINES (DX8_GFX_VBLANK_SCANLINES / 2)

#define DX8_GFX_VBLANK_START            \
  (((DX8_GFX_SCANLINES-DX8_GFX_VBLANK_TOP_SCANLINES-1)*DX8_GFX_CYCLES_PER_SCANLINE)+(DX8_GFX_RESOLUTION-DX8_GFX_HBLANK_LEFT_PX)/DX8_GFX_PIXELS_PER_GFX_CYCLE)
#define DX8_GFX_VBLANK_TOP_CYCLES       (DX8_GFX_CYCLES_PER_FRAME - DX8_GFX_VBLANK_START)
#define DX8_GFX_VBLANK_BOTTOM_CYCLES    (DX8_GFX_VBLANK_TOP_CYCLES + DX8_GFX_CYCLES_PER_SCANLINE * DX8_GFX_HEIGHT)
#define DX8_GFX_VBLANK_CYCLES           (DX8_GFX_VBLANK_TOP_CYCLES + DX8_GFX_VBLANK_BOTTOM_CYCLES)

#define DX8_GFX_CYCLES_PER_VISIBLE_AREA (DX8_GFX_CYCLES_PER_FRAME - DX8_GFX_VBLANK_CYCLES)

#define DX8_CLOCK_GPU                   (DX8_GFX_CYCLES_PER_FRAME)
#define DX8_CLOCK_CPU                   (DX8_GFX_CYCLES_PER_FRAME * 8)
#define DX8_PAL_HZ                      (50.125)

#define DX8_CLOCK_GPU_MZ                ((DX8_CLOCK_GPU * DX8_PAL_HZ) / 1000000.0)
#define DX8_CLOCK_CPU_MZ                ((DX8_CLOCK_CPU * DX8_PAL_HZ) / 1000000.0)

// Old style of constants
#include <dx8a/dx8a_Constants.inc>
#include <dx8a/dx8a_Scancodes.inc>
#include <dx8a/dx8a_Interrupts.inc>
